const header1 = document.querySelector('#header-1') 
const header2 = document.querySelector('#header-2') 
const header3 = document.querySelector('#header-3') 
const body1 = document.querySelector('#body-1') 
const body2 = document.querySelector('#body-2') 
const body3 = document.querySelector('#body-3') 
const body4 = document.querySelector('#body-4') 
const footer1 = document.querySelector('#footer-1') 
const footer2 = document.querySelector('#footer-2') 
const footer3 = document.querySelector('#footer-3') 
const footer4 = document.querySelector('#footer-4')

const preview = document.querySelector('#preview')
window.addEventListener('DOMContentLoaded', loadPreview)